### PR TITLE
631 defect returning to filled out quiz

### LINKED ISSUE #631: Defect: Returning to Filled out Quiz
**Bug Description**
When going through any lab, completing the quiz, leaving, then going back causes a blank screen to appear. Instead of being directed back to the quiz results a blank page forces users to refresh the website. May be an issue with trying to access a complete quiz.

**To Reproduce**

1. Choose a lab off the website all.rit.edu
2. Click through pages until you arrive at the quiz
3. Complete the quiz
4. Click back to reinforcement section
5. Return to quiz
   **Expected behavior**
   The completed quiz should pop up, instead a blank page greets you

Desktop (please complete the following information):

OS: Windows 11
Browser: Chrome

### PR DESCRIPTION
**Pull request by ConnerDeFeo**
- [ ] No discrepancies across browsers. Eg. chrome vs safari
- [ ] Pages pass W3C Validation for HTML (https://validator.w3.org)
- [ ] CSS (https://jigsaw.w3.org/css-validator/)
- [ ] Google sign-in is operational
- [ ] Accessibility functions
- [ ] Pages can scale without distorting page
- [ ] No dead links
- [ ] Navbar is consistent across the site
- [ ] Pages are screen-reader accessible
- [ ] Contrast meets standards for accessibility
- [ ] Pages are keyboard accessible
- [ ] Passes WAVE Evaluation Tool chrome extension

### CODE REVIEW

File: client/src/components/quiz/components/QuizHandler.jsx [hunk 1]
```diff
@@ -16,32 +16,18 @@ const QuizHandler = (props) => {
...
 
   useEffect(() => {
     setCurrentLab(props.labId);
     if (!props.isFinalQuiz) {
       const quiz = props.quizQuestions;
       const quizAnswers = props.quizQuestions[currentQuestionCursor].answers;
-      setQuestions(quiz);
+      props.setQuestions(quiz);
       setAnswerOption(quizAnswers);
+      console.log(props.questions);
```
Comment (JackyFTW) [inline client/src/components/quiz/components/QuizHandler.jsx]: Pls remove the console.log, then I'll merge after

**Review by JackyFTW — CHANGES_REQUESTED** [review]

File: client/src/components/quiz/components/QuizHandler.jsx (hunk 1 above)
Comment (ConnerDeFeo) [reply client/src/components/quiz/components/QuizHandler.jsx]: removed

**Review by JackyFTW — APPROVED** [review]
LGTM

**Review by shmowen — APPROVED** [review]
fire change, thanks boss
