### PR TITLE
328 defect typo in lab 4 exercise

### LINKED ISSUE #328: Defect: Typo in Lab 4 Exercise
**Describe the bug**
There is a typo in the blue box of the exercise end screen

### PR DESCRIPTION
**Pull request by dm9965**
- [ ] No discrepancies across browsers. Eg. chrome vs safari
- [ ] Pages pass W3C Validation for HTML (https://validator.w3.org)
- [ ] CSS (https://jigsaw.w3.org/css-validator/)
- [ ] Google sign-in is operational
- [ ] Accessibility functions
- [ ] Pages can scale without distorting page
- [ ] No dead links
- [ ] Navbar is consistent across the site
- [ ] Pages are screen-reader accessible
- [ ] Contrast meets standards for accessibility
- [ ] Pages are keyboard accessible
- [ ] Passes WAVE Evaluation Tool chrome extension

### CODE REVIEW

File: client/src/components/exercise/lab4/pages/Finish.js [hunk 1]
```diff
@@ -25,11 +25,11 @@ class Finish extends Component {
     return (
       <Fragment>
         <div>
-          <AppBar position="static" className="appBar">
+          <AppBar position="static" className="appBar tw-items-center">
```
Comment (AndreasLc1103) [inline client/src/components/exercise/lab4/pages/Finish.js:28]: Good one bud

Comment (AndreasLc1103) [inline client/src/components/exercise/lab4/pages/Finish.js:28]: Good one bud

**Review by AndreasLc1103 — APPROVED** [review]
