### PR TITLE
1337 defect pie chart is not accessible

### LINKED ISSUE #1337: Defect: Pie Chart is Not Accessible
# Pie Chart is Not Accessible

## Bug and Behavior
Add alt tags and relevant accessibility features to the pie chart component (like values for each key in the legend, title, etc).

## To Reproduce
1. [Step 1]
2. [Step 2]

## Screenshots
[If applicable, add screenshots to help explain the problem]

## Enviornment Info
- Device: [e.g. macbook air 2024]
- OS: [e.g. macOS]

## Additional context
[Add any other context about the problem here]

### PR DESCRIPTION
**Pull request by wlh3903**
Added more descriptive aria-label to Pie Charts
- [ ] No discrepancies across browsers (ex: chrome vs safari)
- [ ] Accessibility functions
- [ ] Pages can scale without distorting page
- [ ] No dead links
- [ ] Navbar is consistent across the site
- [ ] Pages are screen-reader accessible
- [ ] Contrast meets standards for accessibility
- [ ] Pages are keyboard accessible
- [ ] Code is cleaned up and bug-free (ex: debug statements removed)

### CODE REVIEW

File: client/src/components/body/Reading/Reading.js [hunk 1]
```diff
@@ -352,6 +378,7 @@ const Reading = (props) => {
                       data={readingData?.piechart.data}
                       options={largeViewPortOptions}
                       height={!isImagine && PIE_SIZE}
+                      aria-label={accessiblePieLabel}
```
Comment (JackyFTW) [inline client/src/components/body/Reading/Reading.js:381]: Let's also add a `role="img"` described as documented by ARIA standards here.

**Review by JackyFTW — CHANGES_REQUESTED** [review]
just make that small change!

**Review by JackyFTW — APPROVED** [review]
LGTM

**Review by JackyFTW — APPROVED** [review]
lgtm

**Review by ejt7508 — APPROVED** [review]
