### PR TITLE
Hotfix: Lab 7 Crash

### LINKED ISSUE #1286: HOTFIX: Lab 7 exercise quiz broken
lab 7 broken

### PR DESCRIPTION
**Pull request by JackyFTW**
- [ ] No discrepancies across browsers (ex: chrome vs safari)
- [ ] Accessibility functions
- [ ] Pages can scale without distorting page
- [ ] No dead links
- [ ] Navbar is consistent across the site
- [ ] Pages are screen-reader accessible
- [ ] Contrast meets standards for accessibility
- [ ] Pages are keyboard accessible
- [ ] Code is cleaned up and bug-free (ex: debug statements removed)

### CODE REVIEW

File: client/src/components/exercise/lab7/pages/AlterationActivity/AlterationQuiz.js [hunk 1]
```diff
@@ -53,10 +56,16 @@ const AlterationQuiz = () => {
         hideCertificate
```
Comment (JackyFTW) [inline client/src/components/exercise/lab7/pages/AlterationActivity/AlterationQuiz.js:56]: This hideCertificate prop on QuizHandler doesn't seem to do anything lol... not related to this crash but it will show the option for a certificate afterward.

**Review by JackyFTW — COMMENTED** [review]
Looks good beside the comment I made

**Review by wlh3903 — APPROVED** [review]
Hotfix LGTM
