### PR TITLE
Fix Multi-Select Quiz Answer Color

### LINKED ISSUE #1343: Defect: Multi-Select Quiz Answer Color
# Multi-Select Quiz Answer Color

## Bug and Behavior
As observed by chow, the multi-select quiz answer color is green rather than blue, seen elsewhere. We do not use bright green for a lot of the UI choices, so this defect can be created to adhere to the blue like in the single select quiz questions.

## To Reproduce
1. [Step 1]
2. [Step 2]

## Screenshots
[If applicable, add screenshots to help explain the problem]

## Enviornment Info
- Device: [e.g. macbook air 2024]
- OS: [e.g. macOS]

## Additional context
[Add any other context about the problem here]

### PR DESCRIPTION
**Pull request by JackyFTW**
Test with any multi-select quiz question: the selected square should now be blue instead of green.

- [ ] No discrepancies across browsers (ex: chrome vs safari)
- [ ] Accessibility functions
- [ ] Pages can scale without distorting page
- [ ] No dead links
- [ ] Navbar is consistent across the site
- [ ] Pages are screen-reader accessible
- [ ] Contrast meets standards for accessibility
- [ ] Pages are keyboard accessible
- [ ] Code is cleaned up and bug-free (ex: debug statements removed)

### CODE REVIEW

File: client/src/components/exercise/lab14/pages/RSAEncryption.js [hunk 1]
```diff
@@ -121,7 +121,7 @@ const RSAEncryption = () => {
     } catch (err) {
       // On some older systems, the 'crypto' library doesn't have full compatibility.
       // Instead of *actually* doing RSA, we fake it and just shuffle some numbers.
-      
+
```
Comment (JackyFTW) [inline client/src/components/exercise/lab14/pages/RSAEncryption.js:124]: FYI this was a linter warning, don't mind it lol

**Review by WiLLzFPS — APPROVED** [review]
LGTM!

**Review by shmowen — APPROVED** [review]
lgtm
