### PR TITLE
1120 story quantum lab fixes and improvements

### LINKED ISSUE #1120: Story: Quantum Lab Fixes and Improvements
# Quantum Lab Fixes and Improvements

As a **professor**, I want **the quantum lab to be better**, so that **Owen has more work to do**.

## Developer Notes and/or Tasks

- [x] Quantum Labs should be under a new category “Quantum Computing”
- [x] Are the images in reading original?  Are they made by someone else?
- [x] The Caesar Cipher page is too complex – it brings in many other concepts such as math notation, mentioning Grover, etc.
- [x] The Caesar Cipher Encryption (activity) Page the buttons look different – use the same style for both.
- [x] I would have like to go back and try another longer word.  I tried “Hello” and it worked ok.
- [x] Restarted the activity and use “Malachowsky” with a bigger number 7.  It broke the “Quantum Computer” tally on the right.  Refreshing the page also broke it.
- [x] “Hello” with 1 showed no advantage for Quantum.  Require a value greater than 1?  Maybe show multiple values instead of letting the user pick?
- [x] On Vigenère Decryption, I entered “Malachowsky” and “asdf” and it worked a bit better, showing the number more on the bottom – perhaps a similar approach for 6 above?  It did also break the graph a little bit – maybe removing the top value and instead labeling the bar makes sense for all these graphs.
- [x] For RSA Encryption, “Malachowsky” and 1600 makes a very long encrypted message, public key, and private key. 
   - [x] Consider allowing these boxes to grow vertically, wrapping the text to allow the user to see the length of these at a glance.  This property could also be applied to the other encryptions in case longer messages are used. 
   - [x] Is the “n = ” needed on the public/private, or is this superfluous?
   - [x] This also appears to have broken the graphs on the second page, though the quantum is just less than a pixel.  
   - [x] This is where labeling the graph bars (8) above could be important. 
   - [x] Another addition to each of these to show the power of quantum could be how much faster numerically quantum is.  This could be as a it’s # times faster, or an estimate to how long each would take.  The Quantum computer would take 14 seconds and the classical computer would take 13000 years or something like that – pretty easy math, but maybe an enhancement to the graph, especially with the more complex algorithms.
- [x] The quiz looks good, but make sure the answers to every question are present in the lab.
- [x] Disallow users to type numbers in the encryption pages
- [x] Hide "Retry Encryption" and "Next" until user presses "Decrypt"
- [x] Define "Encryption Key" in Vigenere Cipher Encryption Page
- [x] Add blurb between OutputBoxes and Chart describing how many attempts each took.
- [ ] Compare diff number in Decryption to real-world scale.
- [x] Make all non-input text boxes un-hoverable

### PR DESCRIPTION
**Pull request by shmowen**
- [ ] No discrepancies across browsers (ex: chrome vs safari)
- [ ] Accessibility functions
- [ ] Pages can scale without distorting page
- [ ] No dead links
- [ ] Navbar is consistent across the site
- [ ] Pages are screen-reader accessible
- [ ] Contrast meets standards for accessibility
- [ ] Pages are keyboard accessible
- [ ] Code is cleaned up and bug-free (ex: debug statements removed)

### CODE REVIEW

File: client/src/components/exercise/lab14/hooks/useDataService.js [hunk 1]
```diff
@@ -0,0 +1,120 @@
...
+  async function handleExerciseUpdate(body, section) {
+    try {
+      const { isComplete, userid } = body;
+      const data = await ExerciseService.fetchExercise({ userid: userid });
+      if (data) {
+        const { isFormRepairComplete, isDatabaseRepairComplete } = data;
+        if (isComplete) {
+          const updatedBody = {
+            userid: body.userid,
+            isFormRepairComplete:
```
Comment (JackyFTW) [inline client/src/components/exercise/lab14/hooks/useDataService.js]: Requires the backend schema for Lab14 to be reviewed & updated alongside this hook to ensure that the proper tracking of sections completed are included rather than these fields from another lab that used "isFormRepairComplete" and "isDatabaseRepairComplete".

**Review by JackyFTW — CHANGES_REQUESTED** [review]

File: server/routes/index.js [hunk 2]
```diff
@@ -208,13 +206,6 @@ router.post('/lab14/exercise/submit', async function(req, res) {
   const id = await ExerciseControllerLab14.postExercise(req);
   res.send(id);
 });
-router.get('/lab14/repair/:userID/:section', async function(req, res) {
```
Comment (JackyFTW) [inline server/routes/index.js]: Now should be able to remove all lab 14 backend repair stuff too (schema, controller, service, etc).

**Review by JackyFTW — CHANGES_REQUESTED** [review]

File: server/routes/index.js (hunk 2 above)
Comment (shmowen) [reply server/routes/index.js]: donezo

**Comment by VAHdz** [comment]
There is a source missing for one of the images in the Vigenère Cipher section other than that looks good!

**Review by JackyFTW — CHANGES_REQUESTED** [review]
Awesome! Some things:

- I feel like the "Entanglement" page should require the user to try it at least once, same with "Superposition" maybe?
- Tab/whitespace characters are valid inputs to encryption/decryption exercises and ends up breaking some stuff. Only allow [a-ZA-Z] maybe?
- The "RSA Keys Generated" section of RSAEncryption overflows quite a lot on mobile.

Otherwise, greast job! :fire: :fire: Let's go

**Comment by shmowen** [comment]
> There is a source missing for one of the images in the Vigenère Cipher section other than that looks good!

I actually made that graph image myself!

File: server/package-lock.json
Comment (JackyFTW) [inline server/package-lock.json:1]: Thanks for those changes! Please revert this change to server/package-lock.json and make sure *not* to install server dependencies with the `--legacy-peer-deps` flag.

**Review by JackyFTW — CHANGES_REQUESTED** [review]
See final comment regarding the commit diff itself

**Review by JackyFTW — APPROVED** [review]
SEND IT
