### PR TITLE
1335 task krutz has more quantum nitpicks

### LINKED ISSUE #1335: Task: Krutz has more quantum nitpicks
# Krutz has more quantum nitpicks

1) Large numbers need to have commas
2) Weird crash on old safari version

### PR DESCRIPTION
**Pull request by shmowen**
- [ ] No discrepancies across browsers (ex: chrome vs safari)
- [ ] Accessibility functions
- [ ] Pages can scale without distorting page
- [ ] No dead links
- [ ] Navbar is consistent across the site
- [ ] Pages are screen-reader accessible
- [ ] Contrast meets standards for accessibility
- [ ] Pages are keyboard accessible
- [ ] Code is cleaned up and bug-free (ex: debug statements removed)

### CODE REVIEW

File: client/src/components/exercise/lab14/pages/RSAEncryption.js [hunk 1]
```diff
@@ -140,6 +165,8 @@ const RSAEncryption = () => {
     let e = publicJwk.e;
     let d = privateJwk.d;
 
+    console.log(publicKey);
```
Comment (JackyFTW) [inline client/src/components/exercise/lab14/pages/RSAEncryption.js]: nit: remove console log then I'll approve

**Review by JackyFTW — CHANGES_REQUESTED** [review]

**Review by JackyFTW — APPROVED** [review]
LGTM lol
