### PR TITLE
Featured Labs Card Widths

### LINKED ISSUE #1528: Defect: Fix Featured Labs Card Widths
# Fix Featured Labs Card Widths

## Bug and Behavior
See home page, the featured lab's are too wide and cause weird image behavior within the featured lab's card.

## To Reproduce
1. [Step 1]
2. [Step 2]

## Screenshots
[If applicable, add screenshots to help explain the problem]

## Enviornment Info
- Device: [e.g. macbook air 2024]
- OS: [e.g. macOS]

## Additional context
[Add any other context about the problem here]

### PR DESCRIPTION
**Pull request by ejt7508**
- Increased gap between featured labs on large screens
- Risk: might still look bad on weird viewports but common ones seem fine

- [ ] No discrepancies across browsers (ex: chrome vs safari)
- [ ] Accessibility functions
- [ ] Pages can scale without distorting page
- [ ] No dead links
- [ ] Navbar is consistent across the site
- [ ] Pages are screen-reader accessible
- [ ] Contrast meets standards for accessibility
- [ ] Pages are keyboard accessible
- [ ] Code is cleaned up and bug-free (ex: debug statements removed)- [ ] - [ ] - [ ] - [ ] - [ ] - [ ] - [ ] - [ ] - [ ] - [ ] - [ ] - [ ] - [ ] - [ ] - [ ] - [ ] - [ ] - [ ] - [ ] - [ ] - [ ] - [ ] - [ ] - [ ] - [ ] - [ ] - [ ] - [ ] - [ ] - [ ] - [ ] - [ ] - [ ] - [ ] - [ ] - [ ] - [ ] - [ ] - [ ] - [ ] - [ ] - [ ]

### CODE REVIEW

File: client/src/components/body/lab/LabGeneration.js [hunk 1]
```diff
@@ -93,7 +93,7 @@ const LabGeneration = (props) => {
     ) {
       return (
         <div
-          className={`tw-grid xs:tw-grid-cols-1 ${progressState === "MY_LABS" ? "md:tw-grid-cols-3" : "md:tw-grid-cols-2"} tw-w-full tw-gap-3`}
+          className={`tw-grid xs:tw-grid-cols-1 ${progressState === "MY_LABS" ? "md:tw-grid-cols-3" : "md:tw-grid-cols-2 lg:tw-gap-32"} tw-w-full tw-gap-3`}
```
Comment (JackyFTW) [inline client/src/components/body/lab/LabGeneration.js]: Use updated CSS in DMs

**Review by JackyFTW — CHANGES_REQUESTED** [review]

**Review by JackyFTW — APPROVED** [review]
lgtm

**Review by wlh3903 — APPROVED** [review]
LGTM
