### PR TITLE
612 Fix Group Lab Assignment/Update/Delete

### LINKED ISSUE #612: Defect: Fix Group Lab Assignment in Profile Page
**Describe the bug**
Educator cannot assign labs to users.

**To Reproduce**
1 - Log in using Googe OAuth2.0
2 - Go to Profile Page
3 - Attempt to Assign a lab to a group

**Expected behavior**
Group will not receive the assigned lab.

**Screenshots**
image

**Desktop (please complete the following information):**

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by dm9965**
- [ ] No discrepancies across browsers. Eg. chrome vs safari
- [ ] Pages pass W3C Validation for HTML (https://validator.w3.org)
- [ ] CSS (https://jigsaw.w3.org/css-validator/)
- [ ] Google sign-in is operational
- [ ] Accessibility functions
- [ ] Pages can scale without distorting page
- [ ] No dead links
- [ ] Navbar is consistent across the site
- [ ] Pages are screen-reader accessible
- [ ] Contrast meets standards for accessibility
- [ ] Pages are keyboard accessible
- [ ] Passes WAVE Evaluation Tool chrome extension

Updated Profile and Login such that user's can now log in on localhost, as well as use the profile page.

### CODE REVIEW

File: client/src/components/body/profilepage/components/GroupForm.js [hunk 1]
```diff
@@ -29,152 +27,126 @@ const GroupForm = (props) => {
...
+        });
+      }
+      setCheckedLabs(initialCheckedState);
     });
-  }
+  }, [assignedLabs]);
+
+  useEffect(() => {
+    console.log(checkedLabs);
+  }, [checkedLabs]);
```
Comment (heathermoses) [inline client/src/components/body/profilepage/components/GroupForm.js]: Can delete this

File: client/src/components/body/profilepage/components/GroupForm.js [hunk 2]
```diff
@@ -29,152 +27,126 @@ const GroupForm = (props) => {
...
+      const formData = new FormData(e.target);
+      const groupName = formData.get("groupName") || "Default Group Name";
+
+      let selectedLabs = Object.keys(checkedLabs)
+        .filter((labID) => checkedLabs[labID])
+        .map((labID) => parseInt(labID));
+
+      if (addMode === "add_instr_grp") {
+        const newGroup = await GroupService.createGroup(user.userid, groupName);
+        console.log("New group created:", newGroup);
```
Comment (heathermoses) [inline client/src/components/body/profilepage/components/GroupForm.js]: Remove

File: server/controllers/UserController.js [hunk 3]
```diff
@@ -2,73 +2,90 @@ const passport = require('passport');
...
-      res.redirect(req.session.url);
-    },
-    );
-  });
+const authenticateCallback = async (req, res) => {
+  try {
+    const data = await UserService.authenticate(req.user.profile);
+    req.session.token = data.usersessionid;
+    await UserService.updateGuestUserId(data.userid, req.session.token);
+    res.status(301);
```
Comment (heathermoses) [inline server/controllers/UserController.js:57]: Why 301?

**Review by heathermoses — APPROVED** [review]
This looks great to me! I tested this by creating a group, editing the group, deleting the group, and enrolling in the group from a different account.

I left a couple cleanup comments, nothing breaking.

File: client/src/components/body/profilepage/Profile.js [hunk 4]
```diff
@@ -17,15 +17,23 @@ const Profile = () => {
   const inProgressLabs = [];
   const completedLabs = [];
 
-  useEffect(() => {
+  const getUserLabs = async () => {
```
Comment (notjoncruz) [inline client/src/components/body/profilepage/Profile.js:20]: why don't we just include this in `useEffect`?

File: client/src/components/body/profilepage/Profile.js [hunk 5]
```diff
@@ -17,15 +17,23 @@ const Profile = () => {
...
     if (state.main.user) {
-      UserService.getUserToDoLabs(state.main.user.userid).then((data) => {
-        setToDoLabs(data);
-      });
-      UserLabService.getUserLabRecords(state.main.user.userid).then((data) => {
-        setLabRecords(data);
-      });
+      try {
+        const toDo = await UserService.getUserToDoLabs(state.main.user.userid);
```
Comment (notjoncruz) [inline client/src/components/body/profilepage/Profile.js:23]: why'd we update this?

File: client/src/components/body/profilepage/components/AddModal.js [hunk 6]
```diff
@@ -48,7 +48,10 @@ const AddModal = (props) => {
     }
   };
 
-  const toggle = () => setModal(!modal);
+  const toggleModal = () => {
+    console.log(modal);
```
Comment (notjoncruz) [inline client/src/components/body/profilepage/components/AddModal.js]: nit: remove console log

File: client/src/components/body/profilepage/components/AddModal.js [hunk 7]
```diff
@@ -57,14 +60,18 @@ const AddModal = (props) => {
           <button
             className="btn btn-second groups__create_btn"
             aria-label="add"
-            onClick={toggle}
+            onClick={() => toggleModal()}
```
Comment (notjoncruz) [inline client/src/components/body/profilepage/components/AddModal.js]: nit: no need for the extra function. just leave it as `onClick={toggleModal}`

File: client/src/components/body/profilepage/components/DeleteModal.js [hunk 8]
```diff
@@ -10,11 +10,11 @@ const DeleteModal = (props) => {
 
   const toggle = () => setModal(!modal);
 
-  const deleteGroup = () => {
-    GroupService.deleteGroup(groupID).then(() => {
+  const deleteGroup = async () => {
+    const deletionCompleted = await GroupService.deleteGroup(groupID);
```
Comment (notjoncruz) [inline client/src/components/body/profilepage/components/DeleteModal.js:14]: same question here, why do we have to await on this?

File: client/src/components/body/profilepage/components/GroupForm.js [hunk 9]
```diff
@@ -29,152 +27,126 @@ const GroupForm = (props) => {
...
+        if (formData.get("groupName") !== props.groupName) {
+          await GroupService.updateGroup(groupID, formData.get("groupName"));
+        }
+
+        if (selectedLabs.length >= 0) {
+          for (const lab in checkedLabs) {
+            if (Array.isArray(assignedLabs) && assignedLabs.length !== 0) {
+              if (
+                !assignedLabs.includes(lab.labID) ||
+                assignedLabs.length === 0
```
Comment (notjoncruz) [inline client/src/components/body/profilepage/components/GroupForm.js]: to arrive in the inner if statement, `assignedLabs.length` must not be equal to `0` (line 83). is there still a need to check whether `assignedLabs.length === 0` (line 86)?

File: client/src/components/body/profilepage/components/GroupForm.js [hunk 10]
```diff
@@ -29,152 +27,126 @@ const GroupForm = (props) => {
...
+
+        await Promise.all(addLabPromises);
+      } else if (addMode === "update_grp_lab" && groupID) {
+        if (formData.get("groupName") !== props.groupName) {
+          await GroupService.updateGroup(groupID, formData.get("groupName"));
+        }
+
+        if (selectedLabs.length >= 0) {
+          for (const lab in checkedLabs) {
+            if (Array.isArray(assignedLabs) && assignedLabs.length !== 0) {
```
Comment (notjoncruz) [inline client/src/components/body/profilepage/components/GroupForm.js]: i am a bit confused, what are we trying to do here?

File: client/src/components/body/profilepage/components/GroupForm.js [hunk 11]
```diff
@@ -29,152 +27,126 @@ const GroupForm = (props) => {
...
+  return (
+    <Form onSubmit={onFormSubmit}>
+      <ModalBody>
+        <FormGroup>
+          <Label for="groupName">Group Name</Label>
+          <Input
+            type="text"
+            name="groupName"
+            id="groupName"
+            defaultValue={groupName || ""}
```
Comment (notjoncruz) [inline client/src/components/body/profilepage/components/GroupForm.js]: nit: `groupName` will default to `Default Group Name`, so I don't think we need the `|| ""`

File: client/src/components/body/profilepage/components/GroupForm.js [hunk 12]
```diff
@@ -29,152 +27,126 @@ const GroupForm = (props) => {
...
+            <div key={lab.id}>
               <Input
-                type="text"
-                name="groupName"
-                id="groupName"
-                placeholder={groupName}
+                type="checkbox"
+                name={lab.id}
+                id={"lab" + lab.id}
+                checked={checkedLabs[lab.id] || false}
```
Comment (notjoncruz) [inline client/src/components/body/profilepage/components/GroupForm.js]: nit: do we need the `|| false`? if `checkedLabs[lab.id]` is undefined, then I think its false. we can also do `!!checkedLabs[lab.id]`

File: server/database/schema.sql [hunk 13]
```diff
@@ -294,16 +305,16 @@ create table userlabcompletion
     primary key (id)
 );
 
-create table users
+CREATE TABLE users
```
Comment (notjoncruz) [inline server/database/schema.sql]: nit: why are these being updated

**Review by notjoncruz — APPROVED** [review]
I haven't tested this locally because I need to setup my environment. I left some comments, but aside from that, LGTM. 

Why were there so many updates to the server?

File: server/controllers/UserController.js (hunk 3 above)
Comment (dm9965) [reply server/controllers/UserController.js:57]: HTTP 301 status indicates permanent redirect, and will update the current URL to the desired redirect location (whatever page the user was one when they logged in)

File: server/database/schema.sql (hunk 13 above)
Comment (dm9965) [reply server/database/schema.sql]: Cleaner coding standard to see the SQL commands vs the table naming commands. Just easier to read.

File: server/controllers/UserController.js (hunk 3 above)
Comment (notjoncruz) [reply server/controllers/UserController.js:57]: I see. I didn't see the `res.redirect(req.session.url)`. nice

File: server/database/schema.sql (hunk 13 above)
Comment (notjoncruz) [reply server/database/schema.sql]: for the sake of convention/standard, can we update these to lowercase? the other definitions are already in lowercase, unless we want to update everything to uppercase.

**Comment by dm9965** [comment]
> I haven't tested this locally because I need to setup my environment. I left some comments, but aside from that, LGTM.
> 
> Why were there so many updates to the server?

I can help you with setup later today if you need it!

File: server/database/schema.sql (hunk 13 above)
Comment (dm9965) [reply server/database/schema.sql]: can do

**Comment by notjoncruz** [comment]
> > I haven't tested this locally because I need to setup my environment. I left some comments, but aside from that, LGTM.
> > Why were there so many updates to the server?
> 
> I can help you with setup later today if you need it!

yeah, let's sync up later today. just tried it locally and I'm getting an error.

image

File: client/src/components/body/profilepage/components/GroupForm.js (hunk 1 above)
Comment (dm9965) [reply client/src/components/body/profilepage/components/GroupForm.js]: Done!

File: client/src/components/body/profilepage/components/GroupForm.js (hunk 2 above)
Comment (dm9965) [reply client/src/components/body/profilepage/components/GroupForm.js]: Done!

File: client/src/components/body/profilepage/Profile.js (hunk 4 above)
Comment (dm9965) [reply client/src/components/body/profilepage/Profile.js:20]: Putting a whole function call inside a useEffect seems like bad practice. Would rather create a separate function to say what it's doing, then place that inside the useEffect.

File: client/src/components/body/profilepage/components/AddModal.js (hunk 6 above)
Comment (dm9965) [reply client/src/components/body/profilepage/components/AddModal.js]: Done!

File: client/src/components/body/profilepage/components/AddModal.js (hunk 7 above)
Comment (dm9965) [reply client/src/components/body/profilepage/components/AddModal.js]: done!

File: client/src/components/body/profilepage/components/GroupForm.js (hunk 9 above)
Comment (dm9965) [reply client/src/components/body/profilepage/components/GroupForm.js]: Extra checks left in on my part from previous development on the groupform. Just removed them and works fine.

File: client/src/components/body/profilepage/components/GroupForm.js (hunk 10 above)
Comment (dm9965) [reply client/src/components/body/profilepage/components/GroupForm.js]: Essentially checking to see if the array, selectedLabs, is greater than 0. This was used as a check in the prior version so i kept it, but it has now been removed and it still works fine.

File: client/src/components/body/profilepage/components/GroupForm.js (hunk 11 above)
Comment (dm9965) [reply client/src/components/body/profilepage/components/GroupForm.js]: True. Removed.

File: client/src/components/body/profilepage/components/GroupForm.js (hunk 12 above)
Comment (dm9965) [reply client/src/components/body/profilepage/components/GroupForm.js]: I left it so it may be more readable for future devs, however the !! operator works as well. Done.

File: client/src/components/body/profilepage/components/DeleteModal.js (hunk 8 above)
Comment (dm9965) [reply client/src/components/body/profilepage/components/DeleteModal.js:14]: promise chaining can be dangerous if it becomes too complex. There were a lot of problems with the User Service and promises inside of other promises when i updated the login functionality, so I plan to update our backend to an async/await style with try/catch blocks vs promise chaining for better error handling and readability.

**Review by heathermoses — APPROVED** [review]

**Comment by notjoncruz** [comment]
Something I noticed:
1. Create a Group with all the labs
2. Enroll in the Group using the code
3. Delete the Group
4. Notice that the assigned labs are still assigned to you, even though the Group was deleted
5. Even though the Group is deleted, and you're not enrolled anymore because it was deleted, you can re-enroll in the Group

I am not sure if this is in scope, but something I noticed.

**Comment by notjoncruz** [comment]
If this is out-of-scope, this PR LGTM.

**Review by notjoncruz — APPROVED** [review]
