### PR TITLE
1123 defect reloading pages briefly shows invalid page

### LINKED ISSUE #1123: Defect: Reloading Pages Briefly Shows "Invalid Page"
# Reloading Pages Briefly Shows "Invalid Page"

## Bug and Behavior
When on a lab page, as an example, reloading the page will cause the main content area to briefly render a misaligned "Invalid Page" header with a loading circle for a small amount of time. Instead, we expect just a loading circle instead. Ideally, this should not cause layout shift too.

## To Reproduce
1. [Step 1]
2. [Step 2]

## Screenshots
Too fast to capture properly

## Enviornment Info
- Device: Laptop
- OS: Windows
- Browser: Chrome

## Additional context
N/A

### PR DESCRIPTION
**Pull request by wlh3903**
- Removed reactstrap default spinner and replaced it with our spinner component
- Added useState hook that doesn't render pages or labs until the lab has been stored
- [ ] No discrepancies across browsers (ex: chrome vs safari)
- [ ] Accessibility functions
- [ ] Pages can scale without distorting page
- [ ] No dead links
- [ ] Navbar is consistent across the site
- [ ] Pages are screen-reader accessible
- [ ] Contrast meets standards for accessibility
- [ ] Pages are keyboard accessible
- [ ] Code is cleaned up and bug-free (ex: debug statements removed)

### CODE REVIEW

File: client/src/App.js [hunk 1]
```diff
@@ -51,6 +51,8 @@ import { stateChange } from "./helpers/Redirect";
 import { actions as appActions } from "./reducers/lab1/AppReducer";
 import useMainStateContext from "./reducers/MainContext";
 import { Spinner } from "reactstrap";
+// import Spinner from "./common/Spinner/Spinner";
```
Comment (JackyFTW) [inline client/src/App.js]: nit: remove commented import statement

**Review by JackyFTW — CHANGES_REQUESTED** [review]
Small change, but otherwise, LGTM

**Review by JackyFTW — APPROVED** [review]
LGTM

**Review by shmowen — APPROVED** [review]
Great work!
